## Numpy

In [1]:
import numpy as np

In [2]:
np1=np.array([1,2,3,4])

In [3]:
np1

array([1, 2, 3, 4])

In [4]:
type(np1)

numpy.ndarray

In [6]:
Mat1=np.array([[1,2],[3,4]])

In [7]:
Mat1

array([[1, 2],
       [3, 4]])

In [8]:
np1.shape

(4,)

In [9]:
Mat1.shape

(2, 2)

In [10]:
Mat1.dtype

dtype('int64')

In [12]:
Mat1[0,0]=5

In [13]:
Mat1

array([[5, 2],
       [3, 4]])

In [15]:
Mat2=np.arange(0,10,1)

In [16]:
Mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
Mat3=np.linspace(0,10,20)

In [18]:
Mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
Mat3.shape

(20,)

In [20]:
Mat4=np.random.rand(5,5)

In [21]:
Mat4

array([[0.52081147, 0.5911778 , 0.31094482, 0.52481706, 0.80514006],
       [0.26751175, 0.00321961, 0.47659716, 0.18570874, 0.01907885],
       [0.52633603, 0.04686671, 0.901485  , 0.05923801, 0.24569246],
       [0.78421059, 0.85452489, 0.18063711, 0.45279063, 0.08996068],
       [0.67196857, 0.25210444, 0.84834299, 0.86265765, 0.80395764]])

In [22]:
Mat5=np.random.randn(5,5)

In [23]:
Mat5

array([[-0.00551862, -0.59866397, -0.11363751,  2.19382085, -0.24020602],
       [-1.00753444, -0.59576269,  0.76403705, -1.0972728 , -0.28645133],
       [-0.12958806,  1.55626961,  0.24292436, -0.56494726, -0.4629935 ],
       [-0.92470019, -0.70845735, -0.70366793, -0.43434885, -0.94566265],
       [-0.28239547, -0.23818838,  0.87758511,  1.4643446 ,  2.21599011]])

In [24]:
Mat5[0,0]

-0.0055186176673283115

In [25]:
Mat5[0,1]

-0.5986639664961748

In [26]:
Mat5[0:3,:]

array([[-0.00551862, -0.59866397, -0.11363751,  2.19382085, -0.24020602],
       [-1.00753444, -0.59576269,  0.76403705, -1.0972728 , -0.28645133],
       [-0.12958806,  1.55626961,  0.24292436, -0.56494726, -0.4629935 ]])